name: Android Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Clone submodules recursively
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Cache Android SDK
      uses: actions/cache@v3.4.2
      with:
        path: |
          ${{ env.ANDROID_HOME }}/platforms
          ${{ env.ANDROID_HOME }}/build-tools
          ${{ env.ANDROID_HOME }}/platform-tools
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('app/build.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-
      
    - name: Install NDK and CMake
      uses: nttld/setup-ndk@v1.5.0
      id: setup-ndk
      with:
        ndk-version: 'r27'
        add-to-path: true
        link-to-sdk: true
        local-cache: true
        
    - name: Cache NDK
      uses: actions/cache@v3
      with:
        path: ${{ steps.setup-ndk.outputs.ndk-path }}
        key: ${{ runner.os }}-ndk-${{ hashFiles('app/build.gradle.kts') }}-${{ hashFiles('app/src/main/cpp/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-ndk-
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.22.1'
        
    - name: Install Ninja build system
      run: sudo apt-get update && sudo apt-get install -y ninja-build
      
    - name: Verify NDK installation
      run: |
        echo "NDK path: ${{ steps.setup-ndk.outputs.ndk-path }}"
        ls -la ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/
        chmod +x ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/*
            
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        gradle-version: wrapper
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
        
    - name: Build with Gradle
      run: ./gradlew assembleDebug --build-cache --info
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rpcs3-android-debug
        path: app/build/outputs/apk/debug/app-debug.apk 
